alias ls="ls --color=auto"
alias l="ls -la"
alias vi="vim"
export PS1="${debian_chroot:+($debian_chroot)}\e[1;39m[\u@\h] \e[0;32m\w \e[1;39m$\e[0;39m "
export USER_42="acazuc"
export MAIL_42="acazuc@student.42.fr"
alias clang="clang-3.5"
alias gcc="clang"
alias clangpp="clang++-3.5"
alias gpp="clangpp"
